apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: expense-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-app
  template:
    metadata:
      labels:
        app: expense-app
    spec:
      containers:
      - name: backend-container
        image: kishoreking90/backend:v1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: backend-config
